try {
    anotherFunction ();

}catch{
    console.log('esto es un error')
}